apiVersion : apps/v1
kind: Deployment
metadata:
  name: "notejam-prod"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "notejam-prod"
  template:
    metadata:
      labels:
        app: "notejam-prod"
    spec:
      containers:
        - name: "notejam-prod"
          image: "myprodacr.azurecr.io/myaks"
          ports:
          - containerPort: 5000