apiVersion: v1
kind: Ingress
metadata:
  name: notejam-prod
  namespace: {{ default "staging" .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
spec:
  rules:
    - host: notejam-{{ default "staging" .Release.Namespace }}.{{ .Values.dns.name }}
      http:
        paths:
          - backend:
              serviceName: notejam-prod
              servicePort: http
            path: /
