apiVersion: v1
kind: Service
metadata:
    name: "notejam-prod7"
    labels:
        app: "notejam-prod"
spec:
    type: LoadBalancer
    ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      name: http
    selector:
        app: "notejam-prod"